from enum import StrEnum


class RuntimeStage(StrEnum):
    BOOT = "BOOT"
    CONFIG_LOADED = "CONFIG_LOADED"
    IBKR_CONNECTED = "IBKR_CONNECTED"
    ACCOUNT_RECONCILED = "ACCOUNT_RECONCILED"
    DISCOVERY_READY = "DISCOVERY_READY"
    MARKET_READY = "MARKET_READY"
    READY = "READY"
    RUNNING = "RUNNING"
    DEGRADED = "DEGRADED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    SAFE_MODE = "SAFE_MODE"
    STOPPED = "STOPPED"


class OrderState(StrEnum):
    INTENT_CREATED = "INTENT_CREATED"
    PRECHECK_PASSED = "PRECHECK_PASSED"
    SUBMITTING = "SUBMITTING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    LIVE = "LIVE"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"
    UNKNOWN_RECONCILING = "UNKNOWN_RECONCILING"


class DecisionAction(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    HOLD = "HOLD"
    EXIT = "EXIT"
    REBALANCE = "REBALANCE"
    NO_ACTION = "NO_ACTION"


class AssetClass(StrEnum):
    EQUITY = "EQUITY"
    ETF = "ETF"
    FX = "FX"
    FUTURES = "FUTURES"
    OPTION = "OPTION"
    FUTURES_OPTION = "FUTURES_OPTION"
    BOND = "BOND"
    FUND = "FUND"
    WARRANT = "WARRANT"
    STRUCTURED = "STRUCTURED"
    UNKNOWN = "UNKNOWN"
